[program:horizon]
process_name=%(program_name)s
command=php /var/webroot/sites/export-products.strateg.ua/app/artisan horizon
numprocs=1
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/var/log/php-fpm/horizon.log
stderr_logfile=/var/log/php-fpm/horizon-error.log
stopsignal=QUIT
stopwaitsecs=200