upload_max_filesize = 60M
post_max_size = 60M

[xdebug]
xdebug.idekey = "PHPSTORM"
xdebug.mode = debug
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.connect_timeout_ms = 1000

[xhprof]
xhprof.output_dir = /var/webroot/sites/ttter.syvak.com/xhprof/runs_data
xhprof.collect_additional_info = 1