[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
chown=www-data:www-data

[supervisord]
nodaemon=false
childlogdir=/tmp
logfile_maxbytes=100MB
logfile_backups=3
loglevel=info
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
user=www-data

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf
