# Вимагає пароль для доступу до Redis
requirepass mB6^jqM4>asFiS?ddE1@

protected-mode yes
loglevel debug
logfile "/var/log/redis.log"
databases 1

# ACL (Access Control Lists)
# We create a user "my_user" with a password "my_user_password".
user jWoaJ7poI3 on >"gT5_puO4+heZ9{sfF3*w" ~* &* +@all